# Generated by Django 3.2 on 2022-05-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='phone',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
