# Generated by Django 3.2 on 2022-05-11 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='curr_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='curr_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productproperty'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='manufactured',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='size',
            field=models.PositiveIntegerField(choices=[(38, '38'), (40, '40'), (42, '42'), (44, '44'), (46, '46')], default=38),
        ),
    ]
