# Generated by Django 3.2 on 2022-05-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220511_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinorder',
            old_name='price',
            new_name='price_per_item',
        ),
        migrations.AddField(
            model_name='productinorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
