# Generated by Django 3.2 on 2022-05-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20220512_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productproperty',
            name='manufactured',
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='color',
            field=models.CharField(choices=[('BK', 'Black'), ('WT', 'White'), ('BL', 'Blue'), ('BR', 'Brown'), ('RD', 'Red'), ('GR', 'Green')], default='BK', max_length=2),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='size',
            field=models.PositiveIntegerField(choices=[(38, '38'), (40, '40'), (42, '42'), (44, '44'), (46, '46'), (120, '120'), (130, '130'), (140, '140'), (150, '150'), (160, '160')], default=38),
        ),
    ]
