# Generated by Django 3.2 on 2022-05-22 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInCartProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('BK', 'Black'), ('WT', 'White'), ('BL', 'Blue'), ('BR', 'Brown'), ('RD', 'Red'), ('GR', 'Green')], default='BK', max_length=2)),
                ('size', models.PositiveIntegerField(choices=[(38, '38'), (40, '40'), (42, '42'), (44, '44'), (46, '46'), (120, '120'), (130, '130'), (140, '140'), (150, '150'), (160, '160')], default=38)),
                ('gender', models.CharField(choices=[('C', 'Child'), ('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='productincart',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productincartproperty'),
        ),
    ]
