# Generated by Django 3.2 on 2022-05-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_delete_productincartproperty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='property',
        ),
        migrations.RemoveField(
            model_name='productincart',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productincart',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='productincart',
            name='size',
        ),
        migrations.AlterField(
            model_name='productincart',
            name='total_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ProductProperty',
        ),
    ]
