# Generated by Django 3.2 on 2022-05-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20220523_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('BK', 'Black'), ('WT', 'White'), ('BL', 'Blue'), ('BR', 'Brown'), ('RD', 'Red'), ('GR', 'Green')], default='BK', max_length=2),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.PositiveIntegerField(choices=[(7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (37, '37'), (38, '38'), (39, '39'), (40, '40'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (46, '46'), (57, '57'), (58, '58'), (59, '59'), (60, '60'), (120, '120'), (130, '130'), (140, '140'), (150, '150'), (160, '160')], default=38),
        ),
    ]
