from django.core.management.base import BaseCommand

from product.models import (
    Product,
    Manufacturer,
)
from category.models import (
    Subcategory,
)


class Command(BaseCommand):

    def handle(self, *args, **options):
        goods = {'Roeckl LONA gloves': {'price': 59,
                                        'count': 9,
                                        'size': '7',
                                        'color': 'RD',
                                        'manufacturer': Manufacturer(id=2),
                                        'subcategory': Subcategory(id=11)},
                 'gloves "TRYON"': {'price': 48,
                                    'count': 8,
                                    'size': '10',
                                    'color': 'BR',
                                    'manufacturer': Manufacturer(id=2),
                                    'subcategory': Subcategory(id=11)},
                 'gloves "BASCO II"': {'price': 64,
                                       'count': 45,
                                       'size': '11',
                                       'color': 'BK',
                                       'manufacturer': Manufacturer(id=1),
                                       'subcategory': Subcategory(id=11)},
                 'gloves "PINA"': {'price': 37,
                                   'count': 67,
                                   'size': '7',
                                   'color': 'BL',
                                   'manufacturer': Manufacturer(id=3),
                                   'subcategory': Subcategory(id=11),
                                   'description': 'Flex Riding Gloves'},
                 'gloves "PASO"': {'price': 57,
                                   'count': 12,
                                   'size': '9',
                                   'color': 'BK',
                                   'manufacturer': Manufacturer(id=4),
                                   'subcategory': Subcategory(id=11),
                                   'description': 'ProTouch Mesh Gloves'},
                 'breeches "MALTA"': {'price': 79,
                                      'count': 17,
                                      'size': '42',
                                      'color': 'RD',
                                      'manufacturer': Manufacturer(id=1),
                                      'subcategory': Subcategory(id=12),
                                      'description': 'Active Women''s Silicone Grip Full Seat Breeches'},

                 'breeches "PERFOMANS"': {'price': 159,
                                          'count': 17,
                                          'size': '40',
                                          'color': 'BK',
                                          'manufacturer': Manufacturer(id=3),
                                          'subcategory': Subcategory(id=12)},

                 'breeches "HENRY"': {'price': 94,
                                      'count': 17,
                                      'size': '46',
                                      'color': 'BL',
                                      'manufacturer': Manufacturer(
                                          id=4),
                                      'subcategory': Subcategory(
                                          id=12)},
                 'breeches "FUN SPORT"': {'price': 114,
                                          'count': 17,
                                          'size': '44',
                                          'color': 'BK',
                                          'manufacturer': Manufacturer(id=4),
                                          'subcategory': Subcategory(id=12)},
                 'breeches "ASTERIA"': {'price': 129,
                                        'count': 17,
                                        'size': '42',
                                        'color': 'BR',
                                        'manufacturer': Manufacturer(
                                            id=2),
                                        'subcategory': Subcategory(
                                            id=12)},
                 'helmet "EQUESTRO FRAME"': {'price': 98,
                                             'count': 3,
                                             'size': '60',
                                             'color': 'BK',
                                             'manufacturer': Manufacturer(id=1),
                                             'subcategory': Subcategory(id=14)},
                 'helmet "ALLEGRA"': {'price': 128,
                                      'count': 12,
                                      'size': '59',
                                      'color': 'BK',
                                      'manufacturer': Manufacturer(id=2),
                                      'subcategory': Subcategory(id=14)},
                 'helmet "SIGMA"': {'price': 79,
                                    'count': 3,
                                    'size': '57',
                                    'color': 'RD',
                                    'manufacturer': Manufacturer(id=3),
                                    'subcategory': Subcategory(id=14)},
                 'helmet "NOMIC"': {'price': 99,
                                    'count': 8,
                                    'size': '58',
                                    'color': 'BR',
                                    'manufacturer': Manufacturer(id=4),
                                    'subcategory': Subcategory(id=14)},
                 'helmet "SMART_BLUE': {'price': 129,
                                        'count': 10,
                                        'size': '59',
                                        'color': 'BL',
                                        'manufacturer': Manufacturer(id=2),
                                        'subcategory': Subcategory(id=14)},
                 'boots "EPSOM"': {'price': 119,
                                   'count': 45,
                                   'size': '39',
                                   'color': 'BK',
                                   'manufacturer': Manufacturer(id=1),
                                   'subcategory': Subcategory(id=13)},
                 'boots "ATLANTIS"': {'price': 89,
                                      'count': 12,
                                      'size': '37',
                                      'color': 'BR',
                                      'manufacturer': Manufacturer(id=2),
                                      'subcategory': Subcategory(id=13)},
                 'boots "HUNTER"': {'price': 124,
                                    'count': 17,
                                    'size': '42',
                                    'color': 'BK',
                                    'manufacturer': Manufacturer(id=3),
                                    'subcategory': Subcategory(id=13)},
                 'boots "LISSUS"': {'price': 84,
                                    'count': 8,
                                    'size': '43',
                                    'color': 'BK',
                                    'manufacturer': Manufacturer(id=4),
                                    'subcategory': Subcategory(id=13)},
                 'saddle pad "COTTON" DR': {'price': 500,
                                            'count': 29,
                                            'size': '',
                                            'color': 'BK',
                                            'manufacturer': Manufacturer(id=1),
                                            'subcategory': Subcategory(id=16),
                                            'description': 'All Purpose Saddle Pad'},

                 'saddle pad "GLACE': {'price': 28,
                                       'count': 11,
                                       'size': '',
                                       'color': 'RD',
                                       'manufacturer': Manufacturer(id=3),
                                       'subcategory': Subcategory(id=16)},
                 'saddle pad "VELVET"': {'price': 59,
                                         'count': 22,
                                         'size': '',
                                         'color': 'GR',
                                         'manufacturer': Manufacturer(id=3),
                                         'subcategory': Subcategory(id=16)},
                 'saddle pad "X-GRIP"': {'price': 79,
                                         'count': 8,
                                         'size': '',
                                         'color': 'BL',
                                         'manufacturer': Manufacturer(id=1),
                                         'subcategory': Subcategory(id=16)},
                 'saddle pad "PRO SPORT"': {'price': 36,
                                            'count': 25,
                                            'size': '',
                                            'color': 'GR',
                                            'manufacturer': Manufacturer(id=2),
                                            'subcategory': Subcategory(id=16)},
                 'saddle "Performans"': {'price': 539,
                                         'count': 17,
                                         'size': '',
                                         'color': 'BR',
                                         'manufacturer': Manufacturer(id=3),
                                         'subcategory': Subcategory(id=15),
                                         'description': 'Leather All Purpose Saddle'},
                 'saddle "Performans"': {'price': 378,
                                         'count': 45,
                                         'size': '',
                                         'color': 'BK',
                                         'manufacturer': Manufacturer(id=1),
                                         'subcategory': Subcategory(id=15)},
                 'saddle "Performans"': {'price': 378,
                                         'count': 9,
                                         'size': '',
                                         'color': 'BK',
                                         'manufacturer': Manufacturer(id=1),
                                         'subcategory': Subcategory(id=15)},
                 'saddle "Performans"': {'price': 378,
                                         'count': 3,
                                         'size': '',
                                         'color': 'BK',
                                         'manufacturer': Manufacturer(id=2),
                                         'subcategory': Subcategory(id=15)},
                 'helmet "EQUESTRO FRAME"': {'price': 450,
                                             'count': 3,
                                             'manufacturer': Manufacturer(id=4),
                                             'subcategory': Subcategory(id=14)}
                 }
        products = [

            'Roeckl Lona Riding gloves'
            'gloves "TRYON"',
            'Lianna Riding Gloves with PU Pal',
            'Flex Riding Gloves',
            'ProTouch Mesh Gloves',
            'Active Women''s Silicone Grip Full Seat Breeches ',
            'breeches "Performans"',
            'helmet "EQUESTRO FRAME"',
            'saddle pad "COTTON" DR',

        ]


for product in products:
    Product.objects.get_or_create(name=product,
                                  curr_price=goods[product]["price"],
                                  curr_count=goods[product]["count"],
                                  manufacturer=goods[product]["manufacturer"],
                                  subcategory=goods[product]["subcategory"]
                                  )
