from django.core.management.base import BaseCommand

from product.models import (
    Product,
    Manufacturer,
)
from category.models import (
    Subcategory,
)


class Command(BaseCommand):

    def handle(self, *args, **options):
        goods = {'Roeckl LONA gloves': {'price': 59,
                                        'count': 9,
                                        'size': 9,
                                        'color': 'RD',
                                        'manufacturer': Manufacturer(id=2),
                                        'subcategory': Subcategory(id=11),
                                        'description': ''},

                 'gloves "TRYON"': {'price': 48,
                                    'count': 8,
                                    'size': 10,
                                    'color': 'BR',
                                    'manufacturer': Manufacturer(id=2),
                                    'subcategory': Subcategory(id=11),
                                    'description': ''},
                 'gloves "BASCO II"': {'price': 64,
                                       'count': 45,
                                       'size': 11,
                                       'color': 'BK',
                                       'manufacturer': Manufacturer(id=1),
                                       'subcategory': Subcategory(id=11),
                                       'description': ''},
                 'gloves "PINA"': {'price': 37,
                                   'count': 67,
                                   'size': 7,
                                   'color': 'BL',
                                   'manufacturer': Manufacturer(id=3),
                                   'subcategory': Subcategory(id=11),
                                   'description': 'Flex Riding Gloves'},
                 'gloves "PASO"': {'price': 57,
                                   'count': 12,
                                   'size': 9,
                                   'color': 'BK',
                                   'manufacturer': Manufacturer(id=4),
                                   'subcategory': Subcategory(id=11),
                                   'description': 'ProTouch Mesh Gloves'},
                 'breeches "MALTA"': {'price': 79,
                                      'count': 17,
                                      'size': 42,
                                      'color': 'RD',
                                      'manufacturer': Manufacturer(id=1),
                                      'subcategory': Subcategory(id=12),
                                      'description': 'Active Women''s Silicone Grip Full Seat Breeches'},

                 'breeches "ALPHA"': {'price': 159,
                                          'count': 17,
                                          'size': 40,
                                          'color': 'BK',
                                          'manufacturer': Manufacturer(id=3),
                                          'subcategory': Subcategory(id=12),
                                      'description': ''},

                 'breeches "HENRY"': {'price': 94,
                                      'count': 17,
                                      'size': 46,
                                      'color': 'BL',
                                      'manufacturer': Manufacturer(
                                          id=4),
                                      'subcategory': Subcategory(
                                          id=12),
                                      'description': ''},
                 'breeches "FUN SPORT"': {'price': 114,
                                          'count': 17,
                                          'size': 44,
                                          'color': 'BK',
                                          'manufacturer': Manufacturer(id=4),
                                          'subcategory': Subcategory(id=12),
                                          'description': ''},
                 'breeches "ASTERIA"': {'price': 129,
                                        'count': 17,
                                        'size': 42,
                                        'color': 'BR',
                                        'manufacturer': Manufacturer(
                                            id=2),
                                        'subcategory': Subcategory(
                                            id=12),
                                        'description': ''},
                 'helmet "EQUESTRO FRAME"': {'price': 98,
                                             'count': 3,
                                             'size': 60,
                                             'color': 'BK',
                                             'manufacturer': Manufacturer(id=1),
                                             'subcategory': Subcategory(id=14),
                                             'description': ''},
                 'helmet "ALLEGRA"': {'price': 128,
                                      'count': 12,
                                      'size': 59,
                                      'color': 'BK',
                                      'manufacturer': Manufacturer(id=2),
                                      'subcategory': Subcategory(id=14),
                                      'description': ''},
                 'helmet "SIGMA"': {'price': 79,
                                    'count': 3,
                                    'size': 57,
                                    'color': 'RD',
                                    'manufacturer': Manufacturer(id=3),
                                    'subcategory': Subcategory(id=14),
                                    'description': ''},
                 'helmet "NOMIC"': {'price': 99,
                                    'count': 8,
                                    'size': 58,
                                    'color': 'BR',
                                    'manufacturer': Manufacturer(id=4),
                                    'subcategory': Subcategory(id=14),
                                    'description': ''},
                 'helmet "SMART_BLUE"': {'price': 129,
                                        'count': 10,
                                        'size': 59,
                                        'color': 'BL',
                                        'manufacturer': Manufacturer(id=2),
                                        'subcategory': Subcategory(id=14),
                                        'description': ''},
                 'boots "EPSOM"': {'price': 119,
                                   'count': 45,
                                   'size': 39,
                                   'color': 'BK',
                                   'manufacturer': Manufacturer(id=1),
                                   'subcategory': Subcategory(id=13),
                                   'description': ''},
                 'boots "ATLANTIS"': {'price': 89,
                                      'count': 12,
                                      'size': 37,
                                      'color': 'BR',
                                      'manufacturer': Manufacturer(id=2),
                                      'subcategory': Subcategory(id=13),
                                      'description': ''},
                 'boots "HUNTER"': {'price': 124,
                                    'count': 17,
                                    'size': 42,
                                    'color': 'BK',
                                    'manufacturer': Manufacturer(id=3),
                                    'subcategory': Subcategory(id=13),
                                    'description': ''},
                 'boots "LISSUS"': {'price': 84,
                                    'count': 8,
                                    'size': 43,
                                    'color': 'BK',
                                    'manufacturer': Manufacturer(id=4),
                                    'subcategory': Subcategory(id=13),
                                    'description': ''},
                 'saddle pad "COTTON" DR': {'price': 500,
                                            'count': 29,
                                            'size': 7,                                            'color': 'BK',
                                            'manufacturer': Manufacturer(id=1),
                                            'subcategory': Subcategory(id=16),
                                            'description': 'All Purpose Saddle Pad'},

                 'saddle pad "GLACE': {'price': 28,
                                       'count': 11,
                                       'size': 8,
                                       'color': 'RD',
                                       'manufacturer': Manufacturer(id=3),
                                       'subcategory': Subcategory(id=16),
                                       'description': ''},
                 'saddle pad "VELVET"': {'price': 59,
                                         'count': 22,
                                         'size': 7,
                                         'color': 'GR',
                                         'manufacturer': Manufacturer(id=3),
                                         'subcategory': Subcategory(id=16),
                                         'description': ''},
                 'saddle pad "X-GRIP"': {'price': 79,
                                         'count': 8,
                                         'size': 9,
                                         'color': 'BL',
                                         'manufacturer': Manufacturer(id=1),
                                         'subcategory': Subcategory(id=16),
                                         'description': ''},
                 'saddle pad "PRO SPORT"': {'price': 36,
                                            'count': 25,
                                            'size': 8,
                                            'color': 'GR',
                                            'manufacturer': Manufacturer(id=2),
                                            'subcategory': Subcategory(id=16),
                                            'description': ''},
                 'saddle "STAR"': {'price': 539,
                                   'count': 17,
                                   'size': 9,
                                   'color': 'BR',
                                   'manufacturer': Manufacturer(id=3),
                                   'subcategory': Subcategory(id=15),
                                   'description': 'Leather All Purpose Saddle'},
                 'saddle "WINTEC"': {'price': 429,
                                     'count': 5,
                                     'size': 7,
                                     'color': 'BK',
                                     'manufacturer': Manufacturer(id=1),
                                     'subcategory': Subcategory(id=15),
                                     'description': ''},
                 'saddle "DASLO"': {'price': 399,
                                    'count': 9,
                                    'size': 7,
                                    'color': 'BK',
                                    'manufacturer': Manufacturer(id=1),
                                    'subcategory': Subcategory(id=15),
                                    'description': ''},
                 'saddle "SYNTHIA"': {'price': 519,
                                      'count': 8,
                                      'size': 9,
                                      'color': 'BK',
                                      'manufacturer': Manufacturer(id=2),
                                      'subcategory': Subcategory(id=15),
                                      'description': ''},
                 'stirrup "BALANSE"': {'price': 99,
                                       'count': 7,
                                       'size': 11,
                                       'color': 'BR',
                                       'manufacturer': Manufacturer(id=4),
                                       'subcategory': Subcategory(id=18),
                                       'description': 'Luton Anatomic Bridle'},
                 'stirrup "ARENA"': {'price': 69,
                                     'count': 9,
                                     'size': 8,
                                     'color': 'BK',
                                     'manufacturer': Manufacturer(id=1),
                                     'subcategory': Subcategory(id=18),
                                     'description': ''},
                 'stirrup "ALUPRO"': {'price': 119,
                                      'count': 21,
                                      'size': 10,
                                      'color': 'WT',
                                      'manufacturer': Manufacturer(id=3),
                                      'subcategory': Subcategory(id=18),
                                      'description': ''},

                 'stirrup "COMFORT"': {'price': 114,
                                      'count': 18,
                                      'size': 9,
                                      'color': '',
                                      'manufacturer': Manufacturer(id=3),
                                      'subcategory': Subcategory(id=18),
                                       'description': ''},
                 'bridle "CHARLOTTE"': {'price': 95,
                                        'count': 14,
                                        'size': 7,
                                        'color': 'BR',
                                        'manufacturer': Manufacturer(id=3),
                                        'subcategory': Subcategory(id=17),
                                        'description': ''},
                 'bridle "SENSATION"': {'price': 209,
                                        'count': 3,
                                        'size': 9,
                                        'color': 'BR',
                                        'manufacturer': Manufacturer(id=3),
                                        'subcategory': Subcategory(id=17),
                                        'description': ''},
                 'bridle "COMPORT"': {'price': 89,
                                      'count': 14,
                                      'size': 8,
                                      'color': 'BK',
                                      'manufacturer': Manufacturer(id=3),
                                      'subcategory': Subcategory(id=17),
                                      'description': ''},
                 'bridle "ERGONOMIC LINE"': {'price': 106,
                                             'count': 6,
                                             'size': 11,
                                             'color': 'BK',
                                             'manufacturer': Manufacturer(id=3),
                                             'subcategory': Subcategory(id=17),
                                             'description': ''}
                 }
        products = [

            'Roeckl LONA gloves',
            'gloves "TRYON"',
            'gloves "BASCO II"',
            'gloves "PINA"',
            'gloves "PASO"',
            'breeches "MALTA"',
            'breeches "ALPHA"',
            'breeches "HENRY"',
            'breeches "FUN SPORT"',
            'breeches "ASTERIA"',
            'helmet "EQUESTRO FRAME"',
            'helmet "ALLEGRA"',
            'helmet "SIGMA"',
            'helmet "NOMIC"',
            'helmet "SMART_BLUE"',
            'boots "EPSOM"',
            'boots "ATLANTIS"',
            'boots "HUNTER"',
            'boots "LISSUS"',
            'saddle pad "COTTON" DR',
            'saddle pad "GLACE',
            'saddle pad "VELVET"',
            'saddle pad "X-GRIP"',
            'saddle pad "PRO SPORT"',
            'saddle "STAR"',
            'saddle "WINTEC"',
            'saddle "DASLO"',
            'saddle "SYNTHIA"',
            'stirrup "BALANSE"',
            'stirrup "ARENA"',
            'stirrup "ALUPRO"',
            'stirrup "COMFORT"',
            'bridle "CHARLOTTE"',
            'bridle "SENSATION"',
            'bridle "COMPORT"',
            'bridle "ERGONOMIC LINE"',

        ]

        for product in products:
            Product.objects.get_or_create(name=product,
                                          curr_price=goods[product]["price"],
                                          curr_count=goods[product]["count"],
                                          size=goods[product]["size"],
                                          color=goods[product]["color"],
                                          manufacturer=goods[product]["manufacturer"],
                                          subcategory=goods[product]["subcategory"],
                                          description=goods[product]["description"]
                                          )
