# Generated by Django 3.2 on 2022-05-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20220511_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
