# Generated by Django 3.2 on 2022-05-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_total_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
